### ISSUE TITLE
MacOS: test/ram - canary broken

### ISSUE THREAD

**Issue by mouse07410** [ntru-hrss/ntru-hrss#2] opened 2020-08-09 03:25 UTC
MacOS Catalina 10.15.6 (64-bit), Xcode-11.6, GCC-10 (same result with Clang)
```
$ make test 2>&1 | tee test-out.txt
./test/test_poly
TEST_SAMPLE_PLUS:	0
./test/test_polymul
TEST_POLY_INV MOD2:	0
TEST_POLY_INV MOD3:	0
TEST_LIFT:	0
./test/test_ntru
ERRORS: 0/100

./test/test_pack
TEST_PACK:	0
./test/test_cshake
c1 c3 69 25 b6 40 9a 04 f1 b5 04 fc bc a9 d8 2b 40 17 27 7c b5 ed 2b 20 65 fc 1d 38 14 d5 aa f5 
./test/test_shake
f4 20 2e 3c 58 52 f9 18 2a 04 30 fd 81 44 f0 a7 4b 95 e7 41 7e ca e1 7d b0 f8 cf ee d0 e3 e6 6e 
f4 20 2e 3c 58 52 f9 18 2a 04 30 fd 81 44 f0 a7 4b 95 e7 41 7e ca e1 7d b0 f8 cf ee d0 e3 e6 6e 
Success!
./test/speed
-- api --

ntru_keypair: 
median: 46674618
average: 47346313

ntru_encaps: 
median: 965537
average: 976848

ntru_decaps: 
median: 2869704
average: 3210112
. . . . .

./test/ram
Canary broken at 14223
```

Complete logs: 
[make-out.txt](https://github.com/ntru-hrss/ntru-hrss/files/5046717/make-out.txt)
[test-out.txt](https://github.com/ntru-hrss/ntru-hrss/files/5046716/test-out.txt)

### Update
Ref impl in https://github.com/joostrijneveld/NTRU-KEM passes all the tests, including `test/ram`.

**Comment by mouse07410** [comment] 2020-08-17 00:28
@joostrijneveld is this repo maintained?

**Comment by joostrijneveld** [comment] 2020-08-17 17:21
This is not a bug. The way to measure RAM is to write canaries to the stack, and then see when the canary is broken.

This repository contains the code of the NTRU-HRSS submission, which has since merged into the NTRU submission. Perhaps [the NTRU code](https://github.com/jschanck/ntru) is more relevant to your interests.

**Closed as completed by joostrijneveld** 2020-08-17 17:21 UTC
